version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: code_deploy-scripts/cleanup.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: code_deploy-scripts/start_server.sh
      timeout: 300
      runas: root
  