version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: code_deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
	  
  ApplicationStart:
    - location: code_deploy_scripts/start_service.sh
      timeout: 300
      runas: root