name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        target: ${{ secrets.TARGET_DIR }}
        port: 22
        source: "."

    - name: Deploy application
      uses: appleboy/ssh-action@master
      env:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
      with:
        script: |
          sudo apt-get -y update
          cd /home/ec2-user/app
          pip install -r requirements.txt
          pip install gunicorn
          export FLASK_APP=application:application
          gunicorn -b 0.0.0.0:5000 -w 4 application:application
        args: -vvv 

